spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.143.202.207:5432/user-info_db
    username: '{cipher}0ec8ce7c14f59bf3c681150e3d2e01f3b2b116cf81a59edc2ea2c0c7bbef9bac'
    password: '{cipher}af849cf7bcc65f71ab25d25c9639bdc05bd38ef6bc9e3a5bbdf04013ef21bac3'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:1234/auth/realms/go-selling-api
          jwk-set-uri: http://localhost:1234/auth/realms/go-selling-api/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
keycloak:
  realm: go-selling-api
  resource: go-selling
  auth-server-url: http://localhost:1234/auth
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'go-selling'
    secret: '2Urkn4FxNDzgFCQK7MkhVBkxZlbZ4xjk'
    provider: secret
file:
  uploadPath: user-info-service/src/main/resources/storage/
openapi:
  service:
    title: user-info-service
    version: 1.0.0
    url: http://localhost:1688

springdoc:
  api-docs:
    path: /user-info-service/v3/api-docs
  swagger-ui:
    path: /user-info-service/swagger-ui.html
    oauth:
      realm: 'go-selling-api'
      clientId: go-selling
      clientSecret: 2Urkn4FxNDzgFCQK7MkhVBkxZlbZ4xjk